### ISSUE TITLE
Education - Stacey

### ISSUE THREAD

**Issue by modlanglais** [modlanglais/gender-fair-app#3]
Please check off each item as you complete it. Once all of the items have been completed, close the issue.

Javascript:
- [x] https://www.learn-js.org/
- [x] http://jsforcats.com/

HTML:
- [x] https://www.w3schools.com/html/default.asp *HOME through Lists + Javascript sections only

Node.js:
- [x] https://github.com/maxogden/art-of-node/#the-art-of-node
- [x] https://www.nodebeginner.org/

Cloudant:
- [x] https://cloud.ibm.com/docs/services/Cloudant?topic=cloudant-ibm-cloudant-basics

GitHub:
- [x] https://lab.github.com/githubtraining/introduction-to-github

**Comment by StaceyMui** [comment]
Completed all of the learning.
